<?php

$def_options = array(

	'bd_setting' => array(

	 	'home_type' => 'blog' ,
   		'exc_length' => '37',
	 	'bg_pattern' => 'default' ,
	 	'layout_type' => 'layout_default' ,
		'skin_color' => 'red' ,
		'newsticker' => '1' ,
		'newsticker_title' => "Don't Miss" ,
		'newsticker_display' => 'lates' ,
		'show_alert_content' => 'Hello World' ,
		'copyrights' => '&#169; Copyright 2013, All Rights Reserved. | Powered by <a href="http://www.wordpress.com">WordPress</a> | Designed by <a href="http://themeforest.net/user/bdayh">bdayh</a>' ,
		'blog_home_post_meta' => '1' ,
		'blog_home_author_meta' => '1' ,
		'blog_home_data_meta' => '1' ,
		'blog_home_tweet' => '1' ,
		'blog_home_fb' => '1' ,
		'blog_home_gp' => '1' ,
		'blog_home_su' => '1' ,
		'blog_home_in' => '1' ,
		'blog_home_pin' => '1' ,
		'topright_display' => 'search' ,
		'top_date' => '1' ,
		'category_desc' => '1' ,
		'category_rss' => '1' ,
		'archives_crumbs' => '1' ,
		'archives_author' => '1' ,
		'archives_display' => 'excerpt' ,
		'archives_pagination' => '1' ,
		'article_crumbs' => '1' ,
		'article_meta_entry' => '1' ,
		'article_author_avatar' => '1' ,
		'article_author' => '1' ,
		'article_date' => '1' ,
		'article_category' => '1' ,
		'article_comments' => '1' ,
		'article_tags' => '1' ,
		'article_meta_pagination' => '1' ,
		'article_author_box' => '1' ,
		'article_socail' => '1' ,
		'article_home_tweet' => '1' ,
		'article_home_fb' => '1' ,
		'article_home_gp' => '1' ,
		'article_home_in' => '1' ,
		'article_related' => '1' ,
		'article_related_numb' => '4' ,
		'related_type' => 'categories' ,
		'related_style' => 'images' ,
		'social_networking' => '1' ,
		'rss_url' => '#' ,
		'article_twitter_sername' => 'google' ,
		'twitter_button_boxy' => '1' ,
		'facebook_button_boxy' => '1' ,
		'googlep_button_boxy' => '1' ,
		'linkedin_button_boxy' => '1' ,
		'stumbleupon_button_boxy' => '1' ,
		'slider_type' => 'cycleslider' ,
		'feature_slider_small_thumb' => '1' ,
		'feature_slider_numb' => '7' ,
		'feature_slider_speed' => '4000' ,
		'feature_slider_animation' => '600' ,
		'feature_display' => 'lates' ,
		'seo_settings' => '1' ,
		'seo_keywords' => 'template, blog, magazine, news, premium' ,
		'notify_theme' => '0' ,
		'background_type' => 'pattern' ,
	)
);
?>